version: "3.9"
services:
  agent:
    build: ./agent
    ports: [ "8080:8080" ]
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AZ_CLIENT_SECRET=${AZ_CLIENT_SECRET}

  slackbot:
    build: ./bot-slack
    ports: [ "3001:3001" ]

  teamsbot:
    build: ./bot-teams
    ports: [ "3002:3002" ]

  web:
    build: ./web-ui
    ports: [ "3000:3000" ]

  opa:
    build: ./opa
    ports: [ "8181:8181" ]

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports: [ "9090:9090" ]
